---
- name: Get instance ec2 facts
  action: ec2_facts
  register: ec2_facts

- include: mysql-server.yml

- name: register sanity check
  shell: "sudo netstat -lnp | grep 3306 | awk '{ print $1 }'"
  register: mysql_sanity

- fail: msg="MySQL port not active"
  when: mysql_sanity.stdout != "tcp6"

- name: Add a tag
  sudo: no
  local_action: ec2_tag resource={{ec2_facts.ansible_facts.ansible_ec2_instance_id}} region='us-west-1' state=present
  args:
    tags:
      MySQL: 5.6
      Installed: true
