---
# tasks file for golang

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: golang

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: golang

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: golang
